### ISSUE TITLE
Hand over to minetest-mods

### ISSUE THREAD

**Issue by webD97** [minetest-mods/streets#112]
Should we hand this over to https://github.com/minetest-mods? I do not have the time required to properly maintain this mod.

**Comment by Thomas--S** [comment]
I don't have time for maintaining this mod either.
So, feel free to initiate a handover to minetest-mods. I would appreciate it though, if I still keep write access to the repo there; maybe I can work on it again in a few months.

**Comment by webD97** [comment]
https://github.com/minetest-mods/minetest-mods.github.io/issues/117

**Comment by Panquesito7** [comment]
I could help in maintaining this mod. I maintain a few other mods as well. 🙂
Do let me know if you need help with that! For major stuff (like converting to a modpack or stuff like that), I'll discuss it with you two.

Let me know what do you think, thanks! 😄

**Comment by webD97** [comment]
I'm looking forward to any contributions :)

**Comment by Panquesito7** [comment]
Awesome, thanks! If I find anything to contribute to, I'll make a PR. 🙂

**Comment by webD97** [comment]
Sure, that's the spirit we need ;) I'm pretty sure this mod might be in need of some love

**Comment by webD97** [comment]
I think this can be closed now :)
