### ISSUE TITLE
Mesh/texture creating issue

### ISSUE THREAD

**Issue by Panquesito7** [minetest-mods/streets#115]
### Description

Using Minetest 5.6.1. Here are the PC specs in case they're needed:

- CPU: Intel Core2 Quad Q9550.
- GPU: AMD Radeon HD 7950.
- 8GB RAM DDR2 800Mhz.
- Microsoft Windows 10 Home 19044.2486 (21H2).

Various nodes (specifically `streets:roadwork_delineator_bottom` and similar nodes) are displaying an unknown mesh/texture.
Even Minetest reports this on `debug.txt`.

```plaintext
2023-02-13 22:45:57: INFO[Main]: Lazily creating item texture and mesh for "streets:roadwork_delineator_light_bottom"
2023-02-13 22:45:57: INFO[Main]: Lazily creating item texture and mesh for "streets:roadwork_delineator_bottom"
```

![screenshot_20230213_231645](https://user-images.githubusercontent.com/51391473/218645937-66869ed1-b0be-4170-adff-f64ac10fb28c.png)

However, this works fine in Minetest 5.5.0 (same PC specs).

![screenshot_20230213_231918](https://user-images.githubusercontent.com/51391473/218646305-8d73b073-f886-4736-a309-7a6409b01bcc.png)

Are you folks experiencing the same issue?
And, is this related to this mod, or the Minetest engine itself?

Thanks. 🙂

**Comment by amelaye** [comment]
I have the same issue :( ...
