### ISSUE TITLE
Error report (mod d/l from Git)

### ISSUE THREAD

**Issue by kilbith** [minetest-mods/streets#31]
16:51:21: ERROR[main]: ========== ERROR FROM LUA ===========
16:51:21: ERROR[main]: Failed to load and run script from 
16:51:21: ERROR[main]: /home/fabien/.minetest/mods/streets/streetsmod/init.lua:
16:51:21: ERROR[main]: cannot open /home/fabien/.minetest/mods/streets/streetsmod/libs/smartfs/smartfs.lua: No files or folders like this
16:51:21: ERROR[main]: stack traceback:
16:51:21: ERROR[main]:  [C]: in function 'dofile'
16:51:21: ERROR[main]:  /home/fabien/.minetest/mods/streets/streetsmod/init.lua:44: in main chunk
16:51:21: ERROR[main]: ======= END OF ERROR FROM LUA ========

**Comment by Routhinator** [comment]
You should be using subtrees and not submodules so the code is committed as part of your project and you still have remote tracking. If the submodule you are depending on is updated after your commit with a breaking change, your module is broken. Released code should not rely on submodules.

**Comment by webdesigner97** [comment]
That is interesting to know. I will change that for the next release. But don't expect it in the near future, I'm too busy with other stuff...
